dbt_learn_repos:
  outputs:
    dev:
      account: NOTTJQI-LX23018
      database: DEMO
      password: Snowflake@12345
      role: Accountadmin
      schema: DEMO_SCHEMA
      threads: 1
      type: snowflake
      user: SNOWMAN
      warehouse: COMPUTE_WH
  target: dev
