dbt_learn_repos:
  outputs:
    dev:
      account: GXVVTMJ-VPB03868
      database: DBT_PRACTICE
      password: Snowflake@12345
      role: Accountadmin
      schema: RAW_LAYER
      threads: 1
      type: snowflake
      user: SNOWMAN
      warehouse: COMPUTE_WH
  target: dev
