SELECT
    C_CUSTKEY,
    TRIM(UPPER(C_NAME)) AS CUSTOMER_NAME,
 
    CASE 
        WHEN C_NAME IS NULL OR C_NAME = '' THEN 'UNKNOWN'
        ELSE LOWER(C_NAME || '@example.com')
    END AS EMAIL,
    
    COALESCE(C_PHONE, 'NO PHONE') AS PHONE_NUMBER,


    C_MKTSEGMENT,
    
    CASE 
        WHEN C_MKTSEGMENT = 'AUTOMOBILE' THEN 'AUTO SEGMENT'
        WHEN C_MKTSEGMENT = 'FURNITURE' THEN 'FURNITURE SEGMENT'
        ELSE 'OTHER SEGMENT'
    END AS SEGMENT_FLAG,


    C_ACCTBAL,


    CASE 
        WHEN C_ACCTBAL >= 10000 THEN 'HIGH VALUE'
        WHEN C_ACCTBAL BETWEEN 1000 AND 9999 THEN 'MEDIUM VALUE'
        ELSE 'LOW VALUE'
    END AS VALUE_TIER,
    CURRENT_DATE - (C_CUSTKEY % 100) AS CREATED_DATE,
FROM BOOTCAMP.RAW_LAYER.CUSTOMER